pub const PROVIDER_NAME: &str = "google";
pub const PROVIDER_EVENT_ID_PROPERTY: &str = "X-GOOGLE-EVENT-ID";
pub const PROVIDER_COLOR_ID_PROPERTY: &str = "X-GOOGLE-COLOR-ID";
pub const PROVIDER_EVENT_TYPE_PROPERTY: &str = "X-GOOGLE-EVENT-TYPE";
